---
- name: "Template a service backend"
  ansible.builtin.template:
    src: sausage-store-backend.service.j2
    dest: /etc/systemd/system/sausage-store-backend.service
  notify:
  - Restart service sausage-store-backend.service

- name: "Template a service frontend"
  ansible.builtin.template:
    src: sausage-store-frontend.service.j2
    dest: /etc/systemd/system/sausage-store-frontend.service
  notify:
  - Restart service sausage-store-frontend.service
